@startuml

class User <<Entity>> {
    *id_key: UUID
    --
    *email: String
    *password: String
    monthly_income: Float
    *monthly_expense: Float
}

class User_Household <<Entity>>{
    *user_id: UUID <<FK>>
    *household_id: UUID <<FK>>
    --
    *user_is_admin: Boolean
    *share_in_household: Float
}

class Household <<Entity>>{
    *id_key: UUID
    --
    *name: String
}

class TransactionClassification <<Entity>>{
    * id_key: UUID
    --
    description: String
    *name: String <<UNIQUE-1>>
    *household_id: UUID <<FK>> <<UNIQUE-1>>

}

class Transaction <<Entity>>{
    *id_key: UUID
    --
    *amount: Float
    *effect: TransactionEffect
    image: Blob?
    *classification: TransactionClassification <<FK>>
    *household_id: UUID <<FK>>

}

enum TransactionEffect {
    POSITIVE
    NEGATIVE
}

@enduml