@startuml

class User <<Entity>> {
    *id_key: UUID
    --
    *email: String
    *password: String
    monthly_income: Float
    *monthly_expense: Float
}

class User_Household <<Entity>>{
    *user_id: UUID <<FK>>
    *household_id: UUID <<FK>>
    --
    *user_is_admin: Boolean
    *share_in_household: Float
}

User "many" -right-* "1" User_Household
User_Household "1" *-right- "many" Household

class Household <<Entity>>{
    *id_key: UUID
    --
    *name: String
}

class TransactionClassification <<Entity>>{
    * id_key: UUID
    --
    description: String
    *name: String <<UNIQUE-1>>
    *household_id: UUID <<FK>> <<UNIQUE-1>>

}

class Transaction <<Entity>>{
    *id_key: UUID
    --
    *amount: Float
    *effect: TransactionEffect
    *date: LocalDateTime
    image: Blob?
    *classification: TransactionClassification <<FK>>
    *household_id: UUID <<FK>>

}

class Transaction_Household {
    *household_id: UUID <<FK>>
    *transaction_id: UUID <<FK>>
    --
    *share_in_transaction: Float
}

Transaction -right- TransactionEffect : > owns
Transaction "many" -up-* "1" Transaction_Household
Household "many" --* "1" Transaction_Household
Transaction  "many" --* "1" TransactionClassification

enum TransactionEffect {
    POSITIVE
    NEGATIVE
}


@enduml